### ISSUE TITLE
Sort By "random" fails

### ISSUE THREAD

**Issue by wezell** [dotCMS/core#7563]
Not sure if this works in 3.0 but in 3.2, this simple widget code throws an error

```
#foreach($con in $dotcontent.pull("+contentType:News +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:SYSTEM_HOST)",10,"random"))
$con.title
#end
```

Here is the error:

```
2015-04-07 12:24:56,399 ERROR com.dotmarketing.velocity.VelocityServlet - #--------------------------------------------------------------------------------------
2015-04-07 12:24:56,399 ERROR com.dotmarketing.viewtools.content.util.ContentUtils - com.dotcms.repackage.org.elasticsearch.action.search.SearchPhaseExecutionException: Failed to execute phase [query_fetch], all shards failed; shardFailures {[nFLv3iOOQ5SSD_2oAUPpVQ][working_20150407121640][0]: SearchParseException[[working_20150407121640][0]: query[ConstantScore(*:*)],from[-1],size[10]: Parse Failure [Failed to parse source [{"size":10,"query":{"match_all":{}},"post_filter":{"fquery":{"query":{"query_string":{"query":"+contenttype:news +(conhost:48190c8c-42c4-46af-8d1a-0cd5db894797 conhost:system_host) +languageid:1 +working:true +deleted:false"}},"_cache":true}},"fields":["inode","identifier"],"sort":[{"_script":{"script":"Math.random()","type":"number"}}]}]]]; nested: NoClassDefFoundError[org/codehaus/groovy/runtime/callsite/CallSiteArray]; nested: ClassNotFoundException[org.codehaus.groovy.runtime.callsite.CallSiteArray]; }
2015-04-07 12:24:57,381 ERROR com.dotmarketing.velocity.VelocityServlet - #--------------------------------------------------------------------------------------
2015-04-07 12:24:57,381 ERROR com.dotmarketing.velocity.VelocityServlet - #

```

**Comment by oarrietadotcms** [comment]
PR: https://github.com/dotCMS/core/pull/7572

**Comment by bryanboza** [comment]
Fixed, Tested on nightly build 2015-04-11 // postgres // FF
