### ISSUE TITLE
XML Tool not working

### ISSUE THREAD

**Issue by DeanGonzalez** [dotCMS/core#15091]
Reproduced on 5.0.0

This code works on 4.3.3 to parse the XML code on the w3schools xml feed page:

```  
#set($myXML = $xmltool.read("https://www.w3schools.com/XML/cd_catalog.xml"))
<table  border="1" style="width:100%;">
  <tr>
    <th><h2>Title</h2></th>
    <th><h2>Artist</h2></th>
    <th><h2>Country</h2></th>
    <th><h2>Company</h2></th>
    <th><h2>Price</h2></th>
    <th><h2>Year</h2></th>
  </tr>
#foreach($cd in $myXML.children().iterator())
  #set($cdXML = $xmltool.parse($cd))
    #if($velocityCount<=5)
     <tr>
      <td>
     $cdXML.TITLE.text </td>
      <td>
      $cdXML.ARTIST.text </td>
      <td>
      $cdXML.COUNTRY.text </td>
      <td>
      $cdXML.COMPANY.text </td>
      <td>
      $cdXML.PRICE.text </td>
      <td>
      $cdXML.YEAR.text</td>
     </tr>
  #end
#end
</table>
```  

However in the 5.0 version, the same code returns with `$code` throws this in the logs

16:58:53.243  ERROR directive.DotParse - Exception rendering dotParse (/Users/will/git/dotcms5/tomcat8/webapps/ROOT/assets/a/9/a95e37ae-13c6-42f0-9266-dd3b583f9bc8/fileAsset/xml-test.vtl) at LIVE/68c7fa74-d223-48f6-ad61-9df111037ec8/10ca3189-8d72-4d63-9b0b-9f15fe802482.fields[line 5, column 1]. Cause of error: Invocation of method 'get' in  class com.dotcms.rendering.velocity.viewtools.XmlTool threw exception java.lang.NoClassDefFoundError: org/jaxen/JaxenException at /Users/will/git/dotcms5/tomcat8/webapps/ROOT/assets/a/9/a95e37ae-13c6-42f0-9266-dd3b583f9bc8/fileAsset/xml-test.vtl[line 63, column 13] @ url:GET//demo.dotcms.com/about-us/index | lang:1 | ip:127.0.0.1 | Admin:false | start:08-10-2018 04:58:25 EDT  ref:http://127.0.0.1:8080/ >LIVE/68c7fa74-d223-48f6-ad61-9df111037ec8/10ca3189-8d72-4d63-9b0b-9f15fe802482.fields
16:59:26.282  ERROR directive.DotParse - Exception rendering dotParse (/Users/will/git/dotcms5/tomcat8/webapps/ROOT/assets/a/9/a95e37ae-13c6-42f0-9266-dd3b583f9bc8/fileAsset/xml-test.vtl) at LIVE/68c7fa74-d223-48f6-ad61-9df111037ec8/10ca3189-8d72-4d63-9b0b-9f15fe802482.fields[line 5, column 1]. Cause of error: Invocation of method 'get' in  class com.dotcms.rendering.velocity.viewtools.XmlTool threw exception java.lang.NoClassDefFoundError: org/jaxen/JaxenException at /Users/will/git/dotcms5/tomcat8/webapps/ROOT/assets/a/9/a95e37ae-13c6-42f0-9266-dd3b583f9bc8/fileAsset/xml-test.vtl[line 63, column 13] @ url:GET//demo.dotcms.com/about-us/index | lang:1 | ip:127.0.0.1 | Admin:false | start:08-10-2018 04:58:25 EDT  ref:http://127.0.0.1:8080/ >LIVE/68c7fa74-d223-48f6-ad61-9df111037ec8/10ca3189-8d72-4d63-9b0b-9f15fe802482.fields
images.githubusercontent.com/1569167/43980998-6555db62-9cad-11e8-8b2d-252c8bb836a4.png">

**Comment by nollymar** [comment]
Adding missing dependency. PR: https://github.com/dotCMS/core/pull/15094

**Comment by bryanboza** [comment]
Fixed, tested on release-5.0.1 and now we are rendering correctly this code

**Comment by DeanGonzalez** [comment]
Passed QA in Master as well - good fix
