### ISSUE TITLE
[LTS Regression] Publishing Queue "Bundles" tab broken after upgrade to 25.07.10_lts_v10 / 24.12.27_lts_v20

### ISSUE THREAD

**Issue by nathan-hildebrandt** [dotCMS/core#35857]
## Problem Statement

After upgrading to `25.07.10_lts_v10` or `24.12.27_lts_v20`, clicking the **Bundles** tab in the Publishing Queue portlet throws a JSP compilation error and the tab fails to load entirely:

```
Only a type can be imported. com.dotcms.repackage.com.google.common.base.CaseFormat resolves to a package
```

**Root cause:** Two changes landed in both LTS releases that were never coordinated:

1. The `dot.guava` artifact (`com.dotcms.lib:dot.guava:11.0.1_2`) was removed from the classpath as part of the #35235 backport (commit `338cb6a5f1` on 25.07.10 LTS, `3f6b6e89a2` on 24.12.27 LTS). This artifact had previously provided `com.dotcms.repackage.com.google.common.base.CaseFormat`.
2. `view_unpushed_bundles.jsp` still has a stale `<%@page import="com.dotcms.repackage.com.google.common.base.CaseFormat"%>` at line 1 — an import that was harmless while `dot.guava` was on the classpath, but is now unresolvable.

The fix already exists on `main` (PR #35362, commit `d373a563b9`, April 17 2026) but was never backported to either LTS branch.

## Steps to Reproduce

1. Upgrade to dotCMS `25.07.10_lts_v10` or `24.12.27_lts_v20`
2. Navigate to the Publishing Queue portlet
3. Click the **Bundles** tab
4. Observe a 500 error / blank page; server logs show JSP compilation failure

## Acceptance Criteria

- [ ] Remove `<%@page import="com.dotcms.repackage.com.google.common.base.CaseFormat"%>` from `view_unpushed_bundles.jsp` on both LTS branches (mirrors the fix in PR #35362)
- [ ] The Bundles tab in the Publishing Queue portlet loads without error on `25.07.10_lts_v10` and `24.12.27_lts_v20`
- [ ] Fix is shipped in 25.07.10_lts_v11 and 24.12.27_lts_v21

## dotCMS Version

- `25.07.10_lts_v10`
- `24.12.27_lts_v20`

## Severity

High — Major functionality broken (Publishing Queue Bundles tab completely inaccessible after upgrade)

## Links

https://dotcms.freshdesk.com/a/tickets/37546
https://dotcms.freshdesk.com/a/tickets/37554

**Comment by dsolistorres** [comment]
Backported the fix for #35373 to both LTS branches:

- `release-25.07.10_lts` → https://github.com/dotCMS/core/commit/08ef20cafb
- `release-24.12.27_lts` → https://github.com/dotCMS/core/commit/2e5ad40589

**Comment by dsilvam** [comment]
Passed QA
