### ISSUE TITLE
Unable the lock a site for editing after upgrade from 1.9 to 3.2

### ISSUE THREAD

**Issue by bryanboza** [dotCMS/core#7597]
We are having an error on console, after you upgrade from 1.9 directly to 3.2.... You cant make changes to the site... Because you are unable to lock for editing 

Here the error: 
TypeError: ContentletAjax.lockContent is not a function

Tested on nightly build 2015-04-15 // Postgres // FF

FYI: this is happen only of FF, tested on chrome and works fine

**Comment by brentgriffin** [comment]
@bryanboza - are you sure this is not an issue with your browser cache?

**Comment by jtesser** [comment]
was thinking that also @brentgriffin

**Comment by bryanboza** [comment]
Something wrong with my instance, after make the upgrade again works fine... Sorry
